name: Dockerize and push to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS
        uses: aws-actions/login@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-west-2'

      - name: Configure AWS CLI
        run: |
          aws configure set default.region us-west-2
          aws configure set default.output json

      - name: Build and push to ECR
        run: |
          docker build -t my-gin-app .
          docker tag my-gin-app:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com/my-gin-app:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com/my-gin-app:latest

      - name: Verify ECR image
        run: |
          aws ecr describe-images --repository-name my-gin-app --image-ids imageTag=latest